version: '3'

services:
  webapp:
    image: zst_online_server
    environment:
      DJANGO_SETTINGS_MODULE: zst_project.settings.prod
    ports:
      - "8000:8000"
    volumes:
      - "$PWD:/web/zst_online_server/"
      - "/var/www/logs/celery:/var/log/celery"
    command: ["./run_web.sh"]
  nginx:
    image: zst_nginx
    ports:
      - "8090:8090"
    volumes:
      - "$PWD:/usr/share/nginx/html/webapp"
    depends_on:
      - webapp