# Generated by Django 3.1.4 on 2020-12-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('expire_time', models.DateTimeField()),
                ('city', models.CharField(max_length=64)),
                ('isp', models.CharField(max_length=64)),
                ('call_count', models.IntegerField()),
                ('failed_count', models.IntegerField()),
            ],
        ),
    ]
