# Generated by Django 3.1.4 on 2020-12-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxymodel',
            name='call_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proxymodel',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
    ]
