# Generated by Django 3.1.4 on 2020-12-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='insert_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
