# Generated by Django 3.0.2 on 2020-05-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='课程名称', max_length=128, verbose_name='课程名称')),
            ],
        ),
    ]
