# Generated by Django 2.2.5 on 2020-10-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='分类名称,英文', max_length=128, unique=True, verbose_name='分类名称,英文')),
                ('label', models.CharField(help_text='分类名称', max_length=128, unique=True, verbose_name='分类名称')),
                ('path', models.TextField(help_text='路径，以/分割', max_length=1000, verbose_name='路径，以/分割')),
                ('parent_id', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='记录名称', max_length=128, verbose_name='记录名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.Category')),
            ],
            options={
                'unique_together': {('name', 'price', 'date')},
            },
        ),
    ]
