---
- hosts: mysql-master
  vars:
    mysql_data_dir_base: /data/mysql/
    mysql_port: 3306
    mysql_base_dir: /opt/mysql-8.0.16-linux-glibc2.12-x86_64/
    install_packages:
      - vim
      - unzip
      - libaio
      - libaio-devel
      - numactl-devel
      - perl-Data-Dumper 
  tasks:
    - name: install packages
      package:
        name: "{{ install_packages }}"
        state: present
      register: install_packages
    
    - debug:
        var: mysql_port
