# Generated by Django 3.1.3 on 2020-11-21 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_update', models.DateTimeField(auto_now=True, null=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('memory', models.CharField(max_length=30)),
                ('cpu', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MySQLSchema',
            fields=[
                ('gmt_update', models.DateTimeField(auto_now=True, null=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('host_ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('schema', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('master', 'master'), ('slave', 'slave')], max_length=64)),
                ('status', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('pending', 'pending')], default='online', max_length=64)),
                ('phy_host', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='schema_info.host')),
            ],
            options={
                'db_table': 'mysql_schema',
            },
        ),
    ]
