# Generated by Django 3.2.3 on 2021-05-22 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleTaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_update', models.DateTimeField(auto_now=True, null=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('task_id', models.CharField(max_length=128)),
                ('task_name', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=64)),
                ('result', models.TextField(max_length=65535)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='waiting', max_length=32)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DbSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_update', models.DateTimeField(auto_now=True, null=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(help_text='库的名称，一个库可能有多个实例。最大长度：64字节', max_length=64, unique=True, verbose_name='数据库名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='数据库创建时间', verbose_name='数据库创建时间')),
            ],
            options={
                'verbose_name': '数据库表',
                'db_table': 't_db_schema',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_update', models.DateTimeField(auto_now=True, null=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('memory', models.CharField(max_length=30)),
                ('cpu', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MySQLInstance',
            fields=[
                ('gmt_update', models.DateTimeField(auto_now=True, null=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('host_ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('role', models.CharField(choices=[('master', 'master'), ('slave', 'slave')], max_length=64)),
                ('status', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('pending', 'pending')], default='online', max_length=64)),
                ('phy_host', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='schema_info.host')),
                ('schema', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='schema_info.dbschema', to_field='name')),
            ],
            options={
                'db_table': 'mysql_schema',
            },
        ),
    ]
