# Generated by Django 3.2.3 on 2021-05-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mysqlinstance',
            table='t_db_instance',
        ),
    ]
