# Generated by Django 3.1.4 on 2020-12-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleTaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_update', models.DateTimeField(auto_now=True, null=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('task_id', models.CharField(max_length=128)),
                ('task_name', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=64)),
                ('result', models.TextField(max_length=65535)),
                ('status', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
