# Generated by Django 3.1.7 on 2021-04-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema_info', '0002_ansibletaskresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansibletaskresult',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='waiting', max_length=32),
        ),
    ]
