# Generated by Django 3.1.7 on 2021-04-17 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schema_info', '0003_auto_20210417_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlschema',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
