# Generated by Django 3.1.7 on 2021-04-17 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schema_info', '0004_mysqlschema_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqlschema',
            name='start_time',
        ),
        migrations.AddField(
            model_name='ansibletaskresult',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
