# Generated by Django 3.1.7 on 2021-04-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema_info', '0005_auto_20210417_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletaskresult',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
