# Generated by Django 3.1.7 on 2021-05-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema_info', '0007_article_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySQLCluster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cluster_id', models.CharField(default='', help_text='请输入集群ID', max_length=64, unique=True, verbose_name='集群ID')),
            ],
        ),
        migrations.CreateModel(
            name='MySQLInstance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('port', models.PositiveSmallIntegerField(default=3407, help_text='请输入实例端口号', verbose_name='实例端口号')),
                ('role', models.CharField(max_length=8)),
                ('cluster_id', models.ForeignKey(db_column='cluster_id', help_text='请选择集群ID', on_delete=django.db.models.deletion.PROTECT, to='schema_info.mysqlcluster', to_field='cluster_id', verbose_name='集群ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
