# Generated by Django 3.1.7 on 2021-05-07 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema_info', '0009_inspectioncluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=111)),
            ],
        ),
        migrations.AddField(
            model_name='mysqlcluster',
            name='business_id',
            field=models.ForeignKey(db_column='business_id', default=1, help_text='请选择业务信息', on_delete=django.db.models.deletion.CASCADE, to='schema_info.businessinfo', verbose_name='业务信息'),
            preserve_default=False,
        ),
    ]
