# Generated by Django 3.2.3 on 2021-05-22 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schema_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSettingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_alarm', models.BooleanField(default=False)),
                ('sql_print_hash', models.CharField(max_length=128, null=True)),
                ('sql_print', models.TextField(null=True)),
                ('query_time', models.FloatField(default=0.0)),
                ('query_count', models.IntegerField(default=0)),
                ('delete', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('global', 'Global'), ('schema', 'Schema'), ('SQL', 'SQL')], max_length=10)),
                ('schema', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema_info.mysqlinstance')),
            ],
        ),
    ]
