# Generated by Django 3.1.4 on 2021-01-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schema_info', '0002_ansibletaskresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSettingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_alarm', models.BooleanField(default=False)),
                ('sql_print_hash', models.CharField(max_length=128)),
                ('sql_print', models.TextField()),
                ('query_time', models.FloatField()),
                ('query_count', models.IntegerField()),
                ('delete', models.BooleanField(default=False)),
                ('schema', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='schema_info.mysqlschema')),
            ],
        ),
    ]
