# Generated by Django 3.1.4 on 2021-01-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema_info', '0002_ansibletaskresult'),
        ('slowsql', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsettingmodel',
            name='schema',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema_info.mysqlschema'),
        ),
    ]
