# Generated by Django 3.1.7 on 2021-04-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowsql', '0002_auto_20210106_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmsettingmodel',
            name='type',
            field=models.CharField(choices=[('global', 'Global'), ('schema', 'Schema'), ('SQL', 'SQL')], max_length=10, null=True),
        ),
    ]
