# Generated by Django 3.1.7 on 2021-04-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowsql', '0003_alarmsettingmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsettingmodel',
            name='query_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alarmsettingmodel',
            name='query_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='alarmsettingmodel',
            name='sql_print_hash',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
