# Generated by Django 3.1.7 on 2021-04-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowsql', '0004_auto_20210418_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsettingmodel',
            name='sql_print',
            field=models.TextField(null=True),
        ),
    ]
