# Generated by Django 3.1.7 on 2021-05-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowsql', '0005_auto_20210424_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsettingmodel',
            name='type',
            field=models.CharField(choices=[('global', 'Global'), ('schema', 'Schema'), ('SQL', 'SQL')], max_length=10),
        ),
    ]
