# Generated by Django 3.0.5 on 2020-05-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=1024, null=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1024, null=True)),
                ('actions', models.ManyToManyField(blank=True, to='user.ActionSet')),
            ],
        ),
        migrations.AddField(
            model_name='zstuser',
            name='actions',
            field=models.ManyToManyField(blank=True, to='user.ActionSet'),
        ),
        migrations.AddField(
            model_name='zstuser',
            name='roles',
            field=models.ManyToManyField(blank=True, to='user.Role'),
        ),
    ]
