# Generated by Django 3.0.2 on 2020-05-08 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200508_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionset',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='user.Permission'),
        ),
    ]
